In [51]:
# Tried code based on https://www.youtube.com/watch?v=InVJWW_NzFY

In [1]:
#importing necessary libraries
import numpy as np
import random
import itertools
import math

In [2]:
pop_size = 6 
#intializing the vector that is going to hold the probabilities of parents being selected with zeros
Ps = [0]*pop_size
# variable to store total population
totpop = []
gen = 3

In [3]:
class GA:
    def generate_population(self,pop_size):
        # each row of the population matrix is the chromosome of the individual
        # intializing population matrix of size pop_size x pop_size with zeros
        population = np.zeros((pop_size,pop_size))
        for i in range(pop_size):
            # random.sample generates unique random numbers and sets it to the population matrix
            population[i] = random.sample(range(0,100),pop_size)
        #random.sample generates float values so converting it into int type
        population = population.astype(int)
        print("INITIALLY : ")
        print()
        return population 

    def FitnessCalc(self,population):
        global Ps
        print("POPULATION : ")
        #printing the population at hand
        print(population)
        print()
        #defining the fitness function vector as row sums of the population matrix, this will be the total distances vector 
        fitnessfn = np.sum(population, axis=1)
        print("FITNESS OF POPULATION : ")
        print()
        print(fitnessfn)
        ffj = 0
        # the probability of the individual being selected or probability of the contribution of the individual 
        # in the population which is calculated by f[i]/sum of all fitnesses from o to pop_size
        for j in range(0,pop_size):
            ffj = ffj + fitnessfn[j]
        for i in range(0,pop_size):
            Ps[i] = fitnessfn[i]/ffj #Ps is the probabilities of getting selected as parents  
        self.selection(population,fitnessfn)
    
    def selection(self,population,fitnessfn):
        global Ps
        temp = Ps.copy()
        tempp = [0]*pop_size
        pscopy = list(Ps.copy())
        pscopy.sort()
        # we are taking pop_size/2 number of individuals whose distances are minimmum
        # we are going by the logic minimum distance maximum fitness
        for i in range(pop_size):
            for j in range(pop_size):
                if(pscopy[i]==temp[j]):
                    tempp[i] = tempp[i] + population[j] 
        # we are deleting the rest Pop_size/2 amount of individuals with maximum distances
        del tempp[math.ceil(pop_size/2):pop_size]
        # we are creating a list of tuples consisting of all the combinations that can be made 
        # using the pop_size/2 individuals
        parents = itertools.combinations(tempp,2)
        p12 = list(parents)
        # We iterate through the above list and take one combination at a time and call the crossover function
        for i in range(len(p12)):
            self.singleptcrossover(p12[i][0],p12[i][1],population)
    
    def singleptcrossover(self,parentone,parenttwo,population):
        childone = []
        childtwo = []
        new_population = []
        # we are generating a random index to select the point/index of crossover
        c1 = np.random.randint(1,len(parentone)-1)
        # crossing over and getting the two children
        childone = np.concatenate((parentone[0:c1], parenttwo[c1:]), axis=None)
        childtwo = np.concatenate((parenttwo[0:c1], parentone[c1:]), axis=None)
        #calling the mmutate function
        self.mutate(childone,childtwo)

    def mutate(self,childone,childtwo):
        # here the algorithm using swap mutation
        temp1 = []
        temp2 = []
        # we are generating two indices whose elements we are gonna swap for the mutation process
        m1 = np.random.randint(1,len(childone))
        m2 = np.random.randint(1,len(childtwo))
        # mutating the two children chromosomes
        while(m1 == m2):
            m2 = np.random.randint(1,len(childtwo))

        temp1 = childone[m1]
        childone[m1] = childone[m2]
        childone[m2] = temp1

        m1 = np.random.randint(0,len(childone))
        m2 = np.random.randint(0,len(childtwo))
        while(m1 == m2):
            m2 = np.random.randint(1,len(childtwo))
        temp2 = childtwo[m1]
        childtwo[m1] = childtwo[m2]
        childtwo[m2] = temp2 
        # we are apprending the children to the totpop as they will act as the population for the next generation
        totpop.append(childone)
        totpop.append(childtwo)    

In [4]:
global Ps,totpop
tsp = GA()
#initial population generation 
p = tsp.generate_population(pop_size)
#fitness calculation of the initial population
tsp.FitnessCalc(p)
# converting the population matrix into a 2d array
p = np.asarray(totpop)
# if the pop_size is an odd number then the new population will have +1 extra individual as while calculating calculation
# if Pop_size/2 population, we are rounding off the pop_size (which is an odd number to the highest near value)
# what we are doing is we are going to be taking the individual with the least fitness here, that is nothing but highest
# or maxinmum distance and we are removing that individual from the population
if((pop_size%2)!=0):
    fn = np.sum(p, axis=1)
    for k in range(len(fn)):
        if(fn[k]==max(fn)):
            ind = k
    newp = np.delete(p,ind,axis=0)
    p = newp
# this part is similar as the top but here the difference is you are doing for multiple generations, with the initial
# population's children population is  being fed in first as the first input and further on, the children population of the 
# the previous generation is fed as input
# the process for the pop_size being odd is the same as above that is being done here
Ps = [0]*pop_size
totpop = []
print("==================================")
for i in range(gen):
    print("GENERATION : ",i+1)
    print()
    tsp.FitnessCalc(p)
    print("==================================")
    p = np.asarray(totpop)
    if((pop_size%2)!=0):
        fn = np.sum(p, axis=1)
        for k in range(len(fn)):
            if(fn[k]==max(fn)):
                ind = k
        newp = np.delete(p,ind,axis=0)
        p = newp
    Ps = [0]*pop_size
    totpop = []

INITIALLY : 

POPULATION : 
[[66 97 42 65  8 44]
 [75 76 54 45 66 63]
 [93 72 22 52 41 23]
 [ 4 35 65 10 64 82]
 [66 77 70 22 44 54]
 [45 22  7 33 82 58]]

FITNESS OF POPULATION : 

[322 379 303 260 333 247]
GENERATION :  1

POPULATION : 
[[45 22  7 10 82 64]
 [ 4 58 65 33 82 35]
 [45 22 23 33 41  7]
 [93 72 52 22 82 58]
 [ 4 52 22 72 41 23]
 [93 10 65 35 64 82]]

FITNESS OF POPULATION : 

[230 277 171 379 214 349]
GENERATION :  2

POPULATION : 
[[45 23 22 72 41 52]
 [ 4 22 23 41 33  7]
 [45 22 23 82 10 64]
 [33 22  7 45 41  7]
 [ 4  7 52 10 82 64]
 [22 45 22 72 41 23]]

FITNESS OF POPULATION : 

[255 130 246 155 219 225]
GENERATION :  3

POPULATION : 
[[ 4 22 23 41 41  7]
 [33 22  7 45 33  7]
 [ 4 10 23 22 82 64]
 [ 7  4 52 41 33  7]
 [33  7 52 64 82 10]
 [ 4 22  7  7 41 45]]

FITNESS OF POPULATION : 

[138 147 205 144 248 126]


In [5]:
# below was taken from 
# https://medium.com/@becmjo/genetic-algorithms-and-the-travelling-salesman-problem-d10d1daf96a1#:~:text=A%20fitness%20function%20calculates%20the,is%20added%2C%20and%20so%20on.
# Step 1. Create an initial population of P chromosomes.

# Step 2. Evaluate the fitness of each chromosome.

# Step 3. Choose P/2 parents from the current population via proportional selection.

# Step 4. Randomly select two parents to create offspring using crossover operator.

# Step 5. Apply mutation operators for minor changes in the results.

# Step 6. Repeat Steps  4 and 5 until all parents are selected and mated.

# Step 7. Replace old population of chromosomes with new one.

# Step 8. Evaluate the fitness of each chromosome in the new population.

# Step 9. Terminate if the number of generations meets some upper bound; otherwise go to Step  3.



In [6]:
# First we ar ecreating initial population
# Then we are calculating the fitness nothing but calculating the distances that is nothing but the row sum
# Here, minimum distance is our "maximum fitness"
# We take populationsize/2 number of individuals with lowest distances and we are going to find the 2 children for 
# each combination of those individuals through crossover and mutation. If population size is an odd number, we are rounding the population/2 to the next highest number
# We get the new population by appending all the children of all the combinations together. If the population size intially was odd,
# since we rounded it off to a higher number, we have one extra individual in the new population. This extra individual we will remove by seeing which individula has maximum distance
# and that individual we will remove. This new population is fed in as inout for the next generation population and so on.